### ISSUE TITLE
感谢大佬，拿你的代码魔改了一点点，抢到了4080公版。

### ISSUE THREAD

**Issue by Tlntin** [zas023/JdBuyer#19]
主要优化了扫码那个配置，默认的我二维码我扫了总登录不上，我改了一下格式从png改成了jpg，然后加了白色边框，就可以扫码了。
定时器那个用的第三方包，写的那个while循环定时器感觉不太好用。
然后加入了停止时间配置。
目前只有命令行版，没有弄界面，有需要的，可以说一声，等我有空了再弄。
https://github.com/Tlntin/JdBuyer

**Comment by Tlntin** [comment]
运行实例：
详细可以看我仓库的Readme
![image](https://user-images.githubusercontent.com/28218658/206904760-74b2c434-7380-4152-8bf1-5b8172b020fc.png)

**Comment by hongyunfei** [comment]
> 运行实例： 详细可以看我仓库的Readme ![图片](https://user-images.githubusercontent.com/28218658/206904760-74b2c434-7380-4152-8bf1-5b8172b020fc.png)

![image](https://user-images.githubusercontent.com/34985241/206966758-499a3b57-a83f-401d-a30e-cc748bc230ab.png)
大佬我这个什么问题

**Comment by Tlntin** [comment]
> > 运行实例： 详细可以看我仓库的Readme ![图片](https://user-images.githubusercontent.com/28218658/206904760-74b2c434-7380-4152-8bf1-5b8172b020fc.png)
> 
> ![image](https://user-images.githubusercontent.com/34985241/206966758-499a3b57-a83f-401d-a30e-cc748bc230ab.png) 大佬我这个什么问题

看日志，可能是物品在代码执行前已经添加到购物车了，你可以手动移出购物车测试一下。
或者，商品没货/未上架，或者还没进入到预约/购买状态，所以无法进行购物车相关的操作。

**Comment by hongyunfei** [comment]
> > > 运行实例： 详细可以看我仓库的Readme ![图片](https://user-images.githubusercontent.com/28218658/206904760-74b2c434-7380-4152-8bf1-5b8172b020fc.png)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/34985241/206966758-499a3b57-a83f-401d-a30e-cc748bc230ab.png) 大佬我这个什么问题
> 
> 看日志，可能是物品在代码执行前已经添加到购物车了，你可以手动移出购物车测试一下。 或者，商品没货/未上架，或者还没进入到预约/购买状态，所以无法进行购物车相关的操作。

我特意选了一个有货的商品测试的，还是提示购物车取消选购失败，购物车提前清空的，换另一个号就下单正常，会不会这个号有验证才这样的显示。

**Comment by Tlntin** [comment]
> > > > 运行实例： 详细可以看我仓库的Readme ![图片](https://user-images.githubusercontent.com/28218658/206904760-74b2c434-7380-4152-8bf1-5b8172b020fc.png)
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/34985241/206966758-499a3b57-a83f-401d-a30e-cc748bc230ab.png) 大佬我这个什么问题
> > 
> > 
> > 看日志，可能是物品在代码执行前已经添加到购物车了，你可以手动移出购物车测试一下。 或者，商品没货/未上架，或者还没进入到预约/购买状态，所以无法进行购物车相关的操作。
> 
> 我特意选了一个有货的商品测试的，还是提示购物车取消选购失败，购物车提前清空的，换另一个号就下单正常，会不会这个号有验证才这样的显示。

有可能，或许你可以试试设置xxx.ini文件里面的支付密码。
我抢购的时候刚开始没设置这个导致下单一直失败，后面设置了才行。

**Comment by Nesxc** [comment]
大佬你这个时间获取不对，能手动设定吗，晚上8点半结束 程序预计8点半开抢 这肯定是抢不到的

**Comment by Tlntin** [comment]
> 大佬你这个时间获取不对，能手动设定吗，晚上8点半结束 程序预计8点半开抢 这肯定是抢不到的

就是手动设定呀。
时间我本来是8点抢8点02结束。但是没抢到。
后面想着半小时后，说不定有人不付款而退货，所以我又设定了8点半的，结果就抢到了。

**Comment by Nesxc** [comment]
> > 大佬你这个时间获取不对，能手动设定吗，晚上8点半结束 程序预计8点半开抢 这肯定是抢不到的
> 
> 就是手动设定呀。 时间我本来是8点抢8点02结束。但是没抢到。 后面想着半小时后，说不定有人不付款而退货，所以我又设定了8点半的，结果就抢到了。

不好意思 眼瞎了 看到了哈哈哈

**Comment by Nesxc** [comment]
> > 大佬你这个时间获取不对，能手动设定吗，晚上8点半结束 程序预计8点半开抢 这肯定是抢不到的
> 
> 就是手动设定呀。 时间我本来是8点抢8点02结束。但是没抢到。 后面想着半小时后，说不定有人不付款而退货，所以我又设定了8点半的，结果就抢到了。

话说大佬 这种可以抢药吗
![image](https://user-images.githubusercontent.com/58645776/207260828-f82b6736-22c0-48e7-87c0-25ac03ed16d7.png)
url是https://item.yiyaojd.com/2943430.html 和京东的不一样

**Comment by Tlntin** [comment]
> > > 大佬你这个时间获取不对，能手动设定吗，晚上8点半结束 程序预计8点半开抢 这肯定是抢不到的
> > 
> > 
> > 就是手动设定呀。 时间我本来是8点抢8点02结束。但是没抢到。 后面想着半小时后，说不定有人不付款而退货，所以我又设定了8点半的，结果就抢到了。
> 
> 话说大佬 这种可以抢药吗 ![image](https://user-images.githubusercontent.com/58645776/207260828-f82b6736-22c0-48e7-87c0-25ac03ed16d7.png) url是https://item.yiyaojd.com/2943430.html 和京东的不一样

理论上可以，不过这个程序应该不行，毕竟域名都不一样了，大概率获取的参数也不一样了。需要改一些配置，相当于重写一个新的了。

**Comment by siyuan-peng** [comment]
感谢分享 手实在抢不过牛牛 对于4080 4090这种预约制的也可以么

**Comment by Tlntin** [comment]
> 感谢分享 手实在抢不过牛牛 对于4080 4090这种预约制的也可以么

4090改成抽签了，所以不一定可以。
4080预约制抢购，可以。

**Comment by siyuan-peng** [comment]
> > 感谢分享 手实在抢不过牛牛 对于4080 4090这种预约制的也可以么
> 
> 4090改成抽签了，所以不一定可以。 4080预约制抢购，可以。

技嘉90还是预shua约hou制 下次试一下 下单间隔和查询间隔要不要调小一点呀 还是默认值就好

**Comment by Tlntin** [comment]
> > > 感谢分享 手实在抢不过牛牛 对于4080 4090这种预约制的也可以么
> > 
> > 
> > 4090改成抽签了，所以不一定可以。 4080预约制抢购，可以。
> 
> 技嘉90还是预shua约hou制 下次试一下 下单间隔和查询间隔要不要调小一点呀 还是默认值就好

建议默认，我试过调小，然后被封ip了/

**Comment by Prurite** [comment]
> > 感谢分享 手实在抢不过牛牛 对于4080 4090这种预约制的也可以么
> 
> 4090改成抽签了，所以不一定可以。 4080预约制抢购，可以。

网页端在线预约 - 抢购模式的可以是吗，比如 https://item.jd.com/100040452006.html ？

**Comment by Tlntin** [comment]
> > > 感谢分享 手实在抢不过牛牛 对于4080 4090这种预约制的也可以么
> > 
> > 
> > 4090改成抽签了，所以不一定可以。 4080预约制抢购，可以。
> 
> 网页端在线预约 - 抢购模式的可以是吗，比如 https://item.jd.com/100040452006.html ？

可以。

**Comment by Prurite** [comment]
> > 网页端在线预约 - 抢购模式的可以是吗？
> 
> 可以。

它只需要设置区域 id 吗，如果账号里一个区域下有多个收货地址需要再在脚本里面指定吗

**Comment by Tlntin** [comment]
> > > 网页端在线预约 - 抢购模式的可以是吗？
> > 
> > 
> > 可以。
> 
> 它只需要设置区域 id 吗，如果账号里一个区域下有多个收货地址需要再在脚本里面指定吗

地址默认是你上次购物下单的地址，貌似改不了。
如果地址下单后不满意，你可以等你抢购成功后，再改地址。

**Comment by f0ghua** [comment]
试了下抢药。总是提示
```
2022-12-14 19:59:59,010 INFO: 100021455115 满足下单条件，开始执行
提交失败:  获取用户订单信息失败(下单商品可能为第三方商品，将切换为普通发票进行尝试)
提交失败:  您多次提交过快，请稍后再试(下单商品可能为第三方商品，将切换为普通发票进行尝试)
提交失败:  获取用户订单信息失败(下单商品可能为第三方商品，将切换为普通发票进行尝试)
```
不知道这是什么问题。需要怎么修改吗?

**Comment by Tlntin** [comment]
> 试了下抢药。总是提示
> 
> ```
> 2022-12-14 19:59:59,010 INFO: 100021455115 满足下单条件，开始执行
> 提交失败:  获取用户订单信息失败(下单商品可能为第三方商品，将切换为普通发票进行尝试)
> 提交失败:  您多次提交过快，请稍后再试(下单商品可能为第三方商品，将切换为普通发票进行尝试)
> 提交失败:  获取用户订单信息失败(下单商品可能为第三方商品，将切换为普通发票进行尝试)
> ```
> 
> 不知道这是什么问题。需要怎么修改吗?

没啥需要修改，这个就是没有库存了，你抢的时候可以顺便看看手机app，看看是不是抢购按钮灰了。
这种情况基本没有办法，耐心等待2分钟，抢不到就只能等下次了。

**Comment by f0ghua** [comment]
> 

谢谢。我看过了，手机上是能看到抢购的，也能点，但是点击进去也是说失败。耐心等待2分钟是什么意思？

**Comment by DaoLuan0721** [comment]
> 运行实例： 详细可以看我仓库的Readme ![image](https://user-images.githubusercontent.com/28218658/206904760-74b2c434-7380-4152-8bf1-5b8172b020fc.png)

大佬你这个zoneinfo模块不存在，好像需要3.9以上的python版本

**Comment by Tlntin** [comment]
> > 
> 
> 谢谢。我看过了，手机上是能看到抢购的，也能点，但是点击进去也是说失败。耐心等待2分钟是什么意思？

等2分钟的意思就是让它运行2分钟再看看。

**Comment by Tlntin** [comment]
> > 运行实例： 详细可以看我仓库的Readme ![image](https://user-images.githubusercontent.com/28218658/206904760-74b2c434-7380-4152-8bf1-5b8172b020fc.png)
> 
> 大佬你这个zoneinfo模块不存在，好像需要3.9以上的python版本

pip instal xxx或者升级python3.9咯。

**Comment by kylin-kai** [comment]
> > 运行实例： 详细可以看我仓库的Readme![图片](https://user-images.githubusercontent.com/28218658/206904760-74b2c434-7380-4152-8bf1-5b8172b020fc.png)
> 
> ![图片](https://user-images.githubusercontent.com/34985241/206966758-499a3b57-a83f-401d-a30e-cc748bc230ab.png) 大佬我这是什么问题

我也是这个问题解决了吗？

**Comment by Tlntin** [comment]
> > > 运行实例： 详细可以看我仓库的Readme![图片](https://user-images.githubusercontent.com/28218658/206904760-74b2c434-7380-4152-8bf1-5b8172b020fc.png)
> > 
> > 
> > ![图片](https://user-images.githubusercontent.com/34985241/206966758-499a3b57-a83f-401d-a30e-cc748bc230ab.png) 大佬我这是什么问题
> 
> 我也是这个问题解决了吗？

![image](https://user-images.githubusercontent.com/28218658/208037227-ee77e4f0-3399-4da6-8ec6-acad8f240b94.png)

**Comment by Ahernz** [comment]
> 主要优化了扫码那个配置，默认的我二维码我扫了总登录不上，我改了一下格式从png改成了jpg，然后加了白色边框，就可以扫码了。 定时器那个用的第三方包，写的那个while循环定时器感觉不太好用。 然后加入了停止时间配置。 目前只有命令行版，没有弄界面，有需要的，可以说一声，等我有空了再弄。 https://github.com/Tlntin/JdBuyer

大佬，我用了你的项目，运行后提示了这个。
C:\Users\11038\Desktop\JdBuyer-main>python JdBuyer.py
Traceback (most recent call last):
  File "C:\Users\11038\Desktop\JdBuyer-main\JdBuyer.py", line 7, in <module>
    from JdSession import Session
  File "C:\Users\11038\Desktop\JdBuyer-main\JdSession.py", line 8, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by kylin-kai** [comment]
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

**Comment by Manchuker1120** [comment]
预约完之后，然后抢购一直说我 没满足条件，这是为啥？

**Comment by Tlntin** [comment]
> > 主要优化了扫码那个配置，默认的我二维码我扫了总登录不上，我改了一下格式从png改成了jpg，然后加了白色边框，就可以扫码了。 定时器那个用的第三方包，写的那个while循环定时器感觉不太好用。 然后加入了停止时间配置。 目前只有命令行版，没有弄界面，有需要的，可以说一声，等我有空了再弄。 https://github.com/Tlntin/JdBuyer
> 
> 大佬，我用了你的项目，运行后提示了这个。 C:\Users\11038\Desktop\JdBuyer-main>python JdBuyer.py Traceback (most recent call last): File "C:\Users\11038\Desktop\JdBuyer-main\JdBuyer.py", line 7, in from JdSession import Session File "C:\Users\11038\Desktop\JdBuyer-main\JdSession.py", line 8, in import requests ModuleNotFoundError: No module named 'requests'
你应该是没跟着文档安装模块
pip install -r xxxxx.txt

**Comment by Tlntin** [comment]
> Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

第一行出现了两个空格，python应该是4个空格等于一个tab键。
简称：检查一下的你的空格。

**Comment by Tlntin** [comment]
> 预约完之后，然后抢购一直说我 没满足条件，这是为啥？

说明没货，耐心等待。

**Comment by juinjonn** [comment]
看起来 抢抗原 好像不太好使  提交订单的时候  提示了 '属于京东客户端专享商品，请您去京东客户端下单购买，感谢'  想想怎么能让识别是 京东端呢 emmmmmm
抢了好几天了  也稍微改了改  加了 和京东时间 校准

**Comment by Tlntin** [comment]
> 

可以试试改User-Agent，哈哈。

**Comment by juinjonn** [comment]
> > 
> 
> 可以试试改User-Agent，哈哈。

嗯 我也再试哈  哈哈哈哈哈哈

**Comment by flyletc** [comment]
满足下单条件，开始执行...... 为什么还是抢不到？

**Comment by Tlntin** [comment]
> 满足下单条件，开始执行...... 为什么还是抢不到？

建议增加密码。
默认程序会自动用京东xx豆，这玩意需要你的用户密码。

**Comment by kylin-kai** [comment]
> > 满足下单条件，开始执行...... 为什么还是抢不到？
> 
> 
> 
> 建议增加密码。
> 
> 默认程序会自动用京东xx豆，这玩意需要你的用户密码。

加了密码也是同样的情况，有没有大佬解决的

**Comment by syymo** [comment]
> 

同样遇到了`提交失败:  请输入支付密码(需要在config.ini文件中配置支付密码)`但是我配置了密码，我打印
```
paymentPwd = self.password
print("-----paymentPwd------")
print(paymentPwd) 这里是None
```

**Comment by NianBroken** [comment]
ERROR: 购物车取消勾选失败
![image](https://user-images.githubusercontent.com/57057288/209344193-4dc8936a-92ca-4da2-8272-da0d46f5a364.png)
