### ISSUE TITLE
[suggestion] 推送登录二维码到 Server 酱进行状态保活

### ISSUE THREAD

**Issue by BelinChung** [zas023/JdBuyer#3]
首先，伸手党非常感谢作者开源这个项目，也是一样准备抢台富士相机
关于登录状态的问题，以前玩过京东 web 端相关的API，很长时间，京东 web 的 session 可以维持很久，可以用于领取一些奖励或者保价。后来京东那边做了技术调整，京东 web 的 session 基本 24 小时不到就会失效，需要频繁登录的监听程序直接废了

我这边有一个想法，碍于对 Python 不熟悉，无法发起 PR，能否在 testSession false 的时候，重新获取登录二维码，并且通过某些推送渠道，将二维码图片通知给监听的人，然后实现手工再登录，完成变相的保活。

以上。

**Comment by XiaoHb233** [comment]
> 熟悉，无法发起 PR，能否在

使用手机端的就也是移动端的cookie保活

**Comment by BelinChung** [comment]
> 使用手机端的就也是移动端的cookie保活

目前是移动端扫码登陆web端，使用的是web端的协议，会存在频繁掉线（session有效期短）的问题

**Comment by zas023** [comment]
感谢大佬提议，但考虑大部分用户只有一个终端，这样推送二维码的话，还得保存图片进行扫码，操作有些繁琐。
不知是否存在一些核心接口每次访问重置session有效期，然后使用定时任务定期保活。

**Comment by BelinChung** [comment]
web jd 协议已经被改了，session有效期非常短，因为 pc web 不是京东核心用户入口，为了打击第三方程序，前一年还是2年直接把 session 有效期置了一个非常短的有效期，而且因为 pc web B/S 模式，肯定是不支持 refresh token 的，也没有这个必要。

推送二维码然后让用户扫码登陆，比我现在跑在服务器里方便太多了，因为没有 GHOME ，我现在都 sz Qrcode.png 出来扫码登陆

**Comment by FodderFish** [comment]
我不到一小时就cookie失效了 监听到库存也无法下单
